apiVersion: apps/v1
kind: Deployment
metadata:
  name: e-neural-facebook
  namespace: prod
  labels:
    cattle.io/creator: norman
    workload.user.cattle.io/workloadselector: deployment-prod-e-neural-facebook
spec:
  replicas: 1
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-prod-e-neural-facebook
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: deployment-prod-e-neural-facebook
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - name: e-neural-facebook
        image: ${CICD_IMAGE}:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 3033
          name: 3033tcp02
          protocol: TCP
      hostAliases:
      - hostnames:
        - magiclead.com.br
        ip: 201.16.139.9
      - hostnames:
        - e-neural.com
        ip: 201.16.139.10